### ISSUE TITLE
Swagger invalide

### ISSUE THREAD

**Issue by brieuc-le-faucheur** [etalab/doc.data.gouv.fr#116]
Bonjour,

Le swagger présenté sur la page : https://doc.data.gouv.fr/api/reference/#/datasets%3D n'est pas valide ~~selon les standards~~ : 

```
Validation failed. Duplicate operation id 'rdf_dataset'

Error: Validation failed. Duplicate operation id 'rdf_dataset'
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

SyntaxError: Validation failed. Duplicate operation id 'rdf_dataset'
    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at validatePath (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:7512)
    at validateSpec (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:7224)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3573)
```

[Lien de l'outil ayant produit ce message](https://apitools.dev/swagger-parser/online/?url=https%3A%2F%2Fwww.data.gouv.fr%2Fapi%2F1%2Fswagger.json)

**Comment by maudetes** [comment]
Bonjour,

Merci pour ce ticket, la correction est cours [dans cette PR](https://github.com/opendatateam/udata/pull/2763).
